export interface Persona {
    cod_pers: number,
    nombres: string,
    t_iden: number,
    nro_id: string,
    ext_id: string,
    dpto_id: number,
    fecha_nac: Date,
    pais_nac:number,
    sexo: string,
    e_civil: string,
    direccion: string,
    tel_dom: string,
    grup_san: string,
    obser: string,
    nro_ruc: string,
    nua: string,
    tit_ben: Date,
    fecha_afil: Date,
    fecha_baja: Date,
    fecha_cadu: Date,
    tipo_afil: number,
    cod_inst: number,
    cod_tper: number,
    cod_tcon: number,
    cod_prof: number,
    estado: string,
    imagen: string,
    usuario:number    
}
